# Generated by Django 5.1.7 on 2025-03-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdocs_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='meeting',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
