# Generated by Django 5.1.7 on 2025-03-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdocs_interface', '0002_documents_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
