# Generated by Django 5.1.7 on 2025-03-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdocs_interface', '0003_documents_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
