# Generated by Django 5.1.7 on 2025-03-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdocs_interface', '0004_documents_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_treatment', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
